name: Deploy Vite App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build with environment variables
        env:
          VITE_SUPABASE_ADMINS: ${{ secrets.SUPA_ADMINS }}
          VITE_SUPABASE_KEY: ${{ secrets.SUPA_PK }}
          VITE_SUPABASE_URL: ${{ secrets.SUPA_URL }}
        run: npm run build

      - name: Deploy (example)
        run: echo "Deploy your build here"
